server:
  port: 7002
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - AuthenticationFilter
      routes[0]:
        id: customer-service
        predicates[0]: Path=/customer-service/api/v1/customers/**
        predicates[1]: Path=/customer-service/api/v1/addresses/**
        predicates[2]: Path=/customer-service/api/v1/cities/**
        predicates[3]: Path=/customer-service/api/v1/individual-customers/**
        predicates[4]: Path=/customer-service/api/v1/districts/**
        uri: lb://customer-service
      routes[1]:
        id: discovery-server
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
        uri: http://localhost:7000
      routes[2]:
        id: identity-service
        predicates[0]: Path=/identity-service/api/v1/**
        uri: lb://identity-service
      routes[3]:
        id: search-service
        predicates[0]: Path=/search-service/api/v1/customers/**
        predicates[1]: Path=/search-service/api/v1/products/**
        uri: lb://search-service
      routes[4]:
        id: account-service
        predicates[0]: Path=/account-service/api/v1/accounts/**
        predicates[1]: Path=/account-service/api/v1/account-types/**
        uri: lb://account-service
      routes[5]:
        id: order-service
        predicates[0]: Path=/order-service/api/v1/individual-orders/**
        uri: lb://order-service
      routes[6]:
        id: invoice-service
        predicates[0]: Path=/invoice-service/api/v1/individual-invoices/**
        uri: lb://invoice-service
      routes[7]:
        id: catalog-service
        predicates[0]: Path=/catalog-service/api/v1/categories/**
        predicates[1]: Path=/catalog-service/api/v1/products/**
        uri: lb://catalog-service
      routes[8]:
        id: basket-service
        predicates[0]: Path=/basket-service/api/v1/baskets/**
        uri: lb://basket-service
